federated: false
clients_data_weight:
- 1.0
# training
batch_size: 1 
gpu_id: 0
gpu_ids:
- '01234567'
lr: 0.0001
num_epoch: 10 
decay_epoch: 8 
seed: 3 
num_workers: 8
# work file
work_dir: ./work_dir
save_log: true
debug: false 
fid: true
fid_dir: ./fid_stats
batch_size_inceptionV3: 8 
# optimizer
beta1: 0.5
beta2: 0.999
# identity loss
identity: true
lambda_identity: 10.0
diff_privacy: false
reg_gan: false
# fedmed-atl
atl: false
auxiliary_rotation: false
auxiliary_translation: false
auxiliary_scaling: false
num_augmentation: 'one' 
#contraD
contraD: false
#general evaluation
general_evaluation: false

