dataset: brats2019
source_domain: t1
target_domain: t2 
fid_dir: ./fid_stats
valid_path: /disk1/medical/brats2019/validation
batch_size: 8 
misaligned: False
size: 256
gpu_id: 3
gpu_ids:
- '01234567'
es_higher_limit: 80 
es_lower_limit: 50
regenerate_data: true
seed: 3