dataset: brats2021
noise_type: gaussian
seed: 3
size: 256 
a_mu: 0.0
a_sigma: 1.0
b_mu: 0.0
b_sigma: 1.0
source_domain: t1
target_domain: t2
data_path: /disk1/medical/brats2021/all
batch_size: 8 
es_higher_limit: 80 
es_lower_limit: 50
gpu_id: 0
gpu_ids:
- '01234567'
num_workers: 8 
work_dir: ./work_dir
save_log: true
debug: false
federated: false
pair_num: 10000
lr: 0.001
#optimizer
beta1: 0.5
beta2: 0.999
#schduler
step_size: 30
gamma: 0.1
#msl
msl_path: ./msl_stats