dataset: ixi
noise_type: gaussian 
seed: 3
size: 256 
a_mu: 0.0
a_sigma: 1.0
b_mu: 0.0
b_sigma: 1.0
source_domain: pd
target_domain: t2
data_path: /disk/medical/ixi
valid_path: /disk/medical/ixi
batch_size: 8 
es_higher_limit: 80 
es_lower_limit: 50
gpu_id: 0
gpu_ids:
- '01234567'
num_workers: 8 
work_dir: ./work_dir
save_log: true
debug: False 
federated: false
bise_stats: false